server:
  port: 8443
  ssl:
    key-store: classpath:examplekeystore.p12
    key-store-password: password
    key-store-type: PKCS12
    key-alias: examplecert
    trust-store: classpath:exampletrust.jks
    trust-store-password: password
    client-auth: want