package com.iicmva;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2018-11-07T07:44:44.981-05:00
 * Generated source version: 3.2.7
 *
 */
@WebServiceClient(name = "VerifyService",
                  wsdlLocation = "file:src/main/resources/wsdl/CoverageVerification.wsdl",
                  targetNamespace = "http://www.iicmva.com/")
public class VerifyService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.iicmva.com/", "VerifyService");
    public final static QName VerifyServiceSoap12 = new QName("http://www.iicmva.com/", "VerifyServiceSoap12");
    public final static QName VerifyServiceSoap = new QName("http://www.iicmva.com/", "VerifyServiceSoap");
    static {
        URL url = null;
        try {
            url = new URL("file:src/main/resources/wsdl/CoverageVerification.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(VerifyService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:src/main/resources/wsdl/CoverageVerification.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public VerifyService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public VerifyService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public VerifyService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public VerifyService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public VerifyService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public VerifyService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns VerifyServiceSoap
     */
    @WebEndpoint(name = "VerifyServiceSoap12")
    public VerifyServiceSoap getVerifyServiceSoap12() {
        return super.getPort(VerifyServiceSoap12, VerifyServiceSoap.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns VerifyServiceSoap
     */
    @WebEndpoint(name = "VerifyServiceSoap12")
    public VerifyServiceSoap getVerifyServiceSoap12(WebServiceFeature... features) {
        return super.getPort(VerifyServiceSoap12, VerifyServiceSoap.class, features);
    }


    /**
     *
     * @return
     *     returns VerifyServiceSoap
     */
    @WebEndpoint(name = "VerifyServiceSoap")
    public VerifyServiceSoap getVerifyServiceSoap() {
        return super.getPort(VerifyServiceSoap, VerifyServiceSoap.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns VerifyServiceSoap
     */
    @WebEndpoint(name = "VerifyServiceSoap")
    public VerifyServiceSoap getVerifyServiceSoap(WebServiceFeature... features) {
        return super.getPort(VerifyServiceSoap, VerifyServiceSoap.class, features);
    }

}
