package com.iicmva;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.2.7
 * 2018-11-07T07:44:44.937-05:00
 * Generated source version: 3.2.7
 *
 */
@WebService(targetNamespace = "http://www.iicmva.com/", name = "VerifyServiceSoap")
@XmlSeeAlso({com.iicmva.coverageverification.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface VerifyServiceSoap {

    @WebMethod(operationName = "VerifyInsurance", action = "http://www.iicmva.com/VerifyInsurance")
    @WebResult(name = "CoverageResponseDocument", targetNamespace = "http://www.iicmva.com/CoverageVerification/", partName = "VerifyInsuranceResult")
    public com.iicmva.coverageverification.CoverageResponseDocument verifyInsurance(
        @WebParam(partName = "CoverageRequest", name = "CoverageRequest", targetNamespace = "http://www.iicmva.com/CoverageVerification/")
        com.iicmva.coverageverification.CoverageRequest coverageRequest
    );
}
